// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         uri: "uri"
 *     }
 */
export interface UtilConvertToMarkdownRequest {
    /** The URI of the resource to convert */
    uri: string;
}
