// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         session_id: "session_id"
 *     }
 */
export interface BashOutputRequest {
    /** Target session ID */
    session_id: string;
    /** Target a specific async command. If not set, uses session-level output. */
    command_id?: string;
    /** Stdout byte offset to read from */
    offset?: number;
    /** Stderr byte offset to read from */
    stderr_offset?: number;
    /** If true, long-poll until new output is available or wait_timeout is reached. */
    wait?: boolean;
    /** Max seconds to wait for new output when wait=true. */
    wait_timeout?: number;
}
