// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         session_id: "session_id",
 *         input: "input"
 *     }
 */
export interface BashWriteRequest {
    /** Target session ID */
    session_id: string;
    /** Target a specific async command. If not set, writes to current command. */
    command_id?: string;
    /** Content to write to the process stdin */
    input: string;
}
