// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         command: "command"
 *     }
 */
export interface BashExecRequest {
    /** Target session ID. If not provided or empty, a new session is created automatically. Reuse the same session_id to continue the same bash session. Only API-level session state is preserved across calls. Note: `cd` or `export` inside a command do NOT affect subsequent calls. */
    session_id?: string;
    /** Shell command to execute */
    command: string;
    /** Working directory (absolute path). Takes effect on every call — if the session already exists, its default working directory is updated for subsequent calls. Use this instead of `cd` when later commands should run in a different directory. */
    exec_dir?: string;
    /** Extra environment variables to inject for this command only. Variables exported inside the command do not persist to later calls. */
    env?: Record<string, string | undefined>;
    /** If true, return immediately with running status. Use /output to poll results. */
    async_mode?: boolean;
    /** HTTP timeout (seconds). Only effective when async_mode=false. If the command does not complete within this time, HTTP returns running status and the command continues in the background. Use /output to get results. */
    timeout?: number;
    /** Hard execution timeout (seconds). When reached, the process is killed and status becomes timed_out. None means no limit. */
    hard_timeout?: number;
    /** Maximum character length for stdout/stderr in the response. When output exceeds this limit, middle truncation is applied (head and tail preserved, middle replaced with a marker). Only effective in sync mode (async_mode=false). Set to 0 to disable truncation. */
    max_output_length?: number;
}
