// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../core/index.js";
import type * as Sandbox from "../../../index.js";

export type Error =
    | Sandbox.skills.listMetadata.Error.UnprocessableEntityError
    | Sandbox.skills.listMetadata.Error._Unknown;

export namespace Error {
    export interface UnprocessableEntityError {
        statusCode: 422;
        content: Sandbox.HttpValidationError;
    }

    export interface _Unknown {
        statusCode: void;
        content: core.Fetcher.Error;
    }

    export interface _Visitor<_Result> {
        unprocessableEntityError: (value: Sandbox.HttpValidationError) => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    unprocessableEntityError: (
        value: Sandbox.HttpValidationError,
    ): Sandbox.skills.listMetadata.Error.UnprocessableEntityError => {
        return {
            content: value,
            statusCode: 422,
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): Sandbox.skills.listMetadata.Error._Unknown => {
        return {
            statusCode: undefined,
            content: fetcherError,
        };
    },

    _visit: <_Result>(
        value: Sandbox.skills.listMetadata.Error,
        visitor: Sandbox.skills.listMetadata.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.statusCode) {
            case 422:
                return visitor.unprocessableEntityError(value.content);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
