// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace BrowserCookies {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BrowserCookies {
    protected readonly _options: BrowserCookies.Options;

    constructor(_options: BrowserCookies.Options) {
        this._options = _options;
    }

    /**
     * Get browser cookies, optionally filtered by URLs (comma-separated).
     *
     * @param {Sandbox.BrowserCookiesGetCookiesRequest} request
     * @param {BrowserCookies.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browserCookies.getCookies({
     *         urls: "urls"
     *     })
     */
    public getCookies(
        request: Sandbox.BrowserCookiesGetCookiesRequest = {},
        requestOptions?: BrowserCookies.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseList, Sandbox.browserCookies.getCookies.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getCookies(request, requestOptions));
    }

    private async __getCookies(
        request: Sandbox.BrowserCookiesGetCookiesRequest = {},
        requestOptions?: BrowserCookies.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseList, Sandbox.browserCookies.getCookies.Error>>> {
        const { urls } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (urls != null) {
            _queryParams.urls = urls;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/cookies",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseList,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browserCookies.getCookies.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browserCookies.getCookies.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Set browser cookies.
     *
     * @param {Sandbox.CookieSetRequest} request
     * @param {BrowserCookies.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browserCookies.setCookies({
     *         cookies: [{
     *                 "key": "value"
     *             }]
     *     })
     */
    public setCookies(
        request: Sandbox.CookieSetRequest,
        requestOptions?: BrowserCookies.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.browserCookies.setCookies.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__setCookies(request, requestOptions));
    }

    private async __setCookies(
        request: Sandbox.CookieSetRequest,
        requestOptions?: BrowserCookies.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.browserCookies.setCookies.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/cookies",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browserCookies.setCookies.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browserCookies.setCookies.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Clear all browser cookies.
     *
     * @param {BrowserCookies.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browserCookies.clearCookies()
     */
    public clearCookies(
        requestOptions?: BrowserCookies.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.browserCookies.clearCookies.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__clearCookies(requestOptions));
    }

    private async __clearCookies(
        requestOptions?: BrowserCookies.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.browserCookies.clearCookies.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/cookies",
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browserCookies.clearCookies.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
