# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action_data import ActionData
    from .action_response import ActionResponse
    from .active_sessions_result import ActiveSessionsResult
    from .active_shell_sessions_result import ActiveShellSessionsResult
    from .annotations import Annotations
    from .annotations_audience_item import AnnotationsAudienceItem
    from .audio_content import AudioContent
    from .available_tool import AvailableTool
    from .bash_command_info import BashCommandInfo
    from .bash_command_status import BashCommandStatus
    from .bash_exec_result import BashExecResult
    from .bash_output_result import BashOutputResult
    from .bash_session_info import BashSessionInfo
    from .blob_resource_contents import BlobResourceContents
    from .browser_info_result import BrowserInfoResult
    from .browser_viewport import BrowserViewport
    from .button import Button
    from .call_tool_result import CallToolResult
    from .captcha_wait_result import CaptchaWaitResult
    from .check_request import CheckRequest
    from .click_action import ClickAction
    from .code_execute_response import CodeExecuteResponse
    from .code_info_response import CodeInfoResponse
    from .code_language_info import CodeLanguageInfo
    from .command_status import CommandStatus
    from .console_record import ConsoleRecord
    from .dependency_command_result import DependencyCommandResult
    from .display_record_result import DisplayRecordResult
    from .double_click_action import DoubleClickAction
    from .drag_rel_action import DragRelAction
    from .drag_to_action import DragToAction
    from .embedded_resource import EmbeddedResource
    from .file_content_encoding import FileContentEncoding
    from .file_download_change_policy import FileDownloadChangePolicy
    from .file_find_result import FileFindResult
    from .file_glob_result import FileGlobResult
    from .file_grep_result import FileGrepResult
    from .file_info import FileInfo
    from .file_list_result import FileListResult
    from .file_operation_error import FileOperationError
    from .file_read_result import FileReadResult
    from .file_replace_result import FileReplaceResult
    from .file_search_result import FileSearchResult
    from .file_upload_result import FileUploadResult
    from .file_write_result import FileWriteResult
    from .glob_file_info import GlobFileInfo
    from .grep_match import GrepMatch
    from .hotkey_action import HotkeyAction
    from .http_validation_error import HttpValidationError
    from .icon import Icon
    from .image_content import ImageContent
    from .jupyter_create_session_response import JupyterCreateSessionResponse
    from .jupyter_execute_response import JupyterExecuteResponse
    from .jupyter_info_response import JupyterInfoResponse
    from .jupyter_output import JupyterOutput
    from .key_down_action import KeyDownAction
    from .key_up_action import KeyUpAction
    from .language import Language
    from .list_tools_result import ListToolsResult
    from .mouse_down_action import MouseDownAction
    from .mouse_up_action import MouseUpAction
    from .move_rel_action import MoveRelAction
    from .move_to_action import MoveToAction
    from .node_js_create_session_response import NodeJsCreateSessionResponse
    from .node_js_delete_session_response import NodeJsDeleteSessionResponse
    from .node_js_execute_response import NodeJsExecuteResponse
    from .node_js_output import NodeJsOutput
    from .node_js_package_info import NodeJsPackageInfo
    from .node_js_runtime_info import NodeJsRuntimeInfo
    from .node_js_session_info import NodeJsSessionInfo
    from .node_js_session_list_response import NodeJsSessionListResponse
    from .node_js_session_response import NodeJsSessionResponse
    from .node_js_update_session_response import NodeJsUpdateSessionResponse
    from .observation_cgroup_snapshot import ObservationCgroupSnapshot
    from .observation_disk_snapshot import ObservationDiskSnapshot
    from .observation_event import ObservationEvent
    from .observation_export_result import ObservationExportResult
    from .observation_live_snapshot import ObservationLiveSnapshot
    from .observation_mode import ObservationMode
    from .observation_process_snapshot import ObservationProcessSnapshot
    from .observation_report_info import ObservationReportInfo
    from .observation_start_result import ObservationStartResult
    from .observation_status import ObservationStatus
    from .observation_stop_result import ObservationStopResult
    from .press_action import PressAction
    from .proxy_bypass_request import ProxyBypassRequest
    from .proxy_diagnose_result import ProxyDiagnoseResult
    from .proxy_health_check import ProxyHealthCheck
    from .proxy_mapping_route import ProxyMappingRoute
    from .proxy_upstream_info import ProxyUpstreamInfo
    from .resolution import Resolution
    from .resource import Resource
    from .resource_link import ResourceLink
    from .response import Response
    from .response_active_sessions_result import ResponseActiveSessionsResult
    from .response_active_shell_sessions_result import ResponseActiveShellSessionsResult
    from .response_bash_exec_result import ResponseBashExecResult
    from .response_bash_output_result import ResponseBashOutputResult
    from .response_bash_session_info import ResponseBashSessionInfo
    from .response_browser_info_result import ResponseBrowserInfoResult
    from .response_call_tool_result_model import ResponseCallToolResultModel
    from .response_call_tool_result_model_data_content_item import (
        ResponseCallToolResultModelDataContentItem,
        ResponseCallToolResultModelDataContentItem_Audio,
        ResponseCallToolResultModelDataContentItem_Image,
        ResponseCallToolResultModelDataContentItem_Resource,
        ResponseCallToolResultModelDataContentItem_ResourceLink,
        ResponseCallToolResultModelDataContentItem_Text,
    )
    from .response_captcha_wait_result import ResponseCaptchaWaitResult
    from .response_code_execute_response import ResponseCodeExecuteResponse
    from .response_code_info_response import ResponseCodeInfoResponse
    from .response_dict import ResponseDict
    from .response_display_record_result import ResponseDisplayRecordResult
    from .response_jupyter_create_session_response import ResponseJupyterCreateSessionResponse
    from .response_jupyter_execute_response import ResponseJupyterExecuteResponse
    from .response_jupyter_info_response import ResponseJupyterInfoResponse
    from .response_list import ResponseList
    from .response_list_bash_session_info import ResponseListBashSessionInfo
    from .response_list_observation_report_info import ResponseListObservationReportInfo
    from .response_list_proxy_mapping_route import ResponseListProxyMappingRoute
    from .response_list_sandbox_hook import ResponseListSandboxHook
    from .response_list_str import ResponseListStr
    from .response_list_tools_result_model import ResponseListToolsResultModel
    from .response_node_js_create_session_response import ResponseNodeJsCreateSessionResponse
    from .response_node_js_delete_session_response import ResponseNodeJsDeleteSessionResponse
    from .response_node_js_execute_response import ResponseNodeJsExecuteResponse
    from .response_node_js_runtime_info import ResponseNodeJsRuntimeInfo
    from .response_node_js_session_list_response import ResponseNodeJsSessionListResponse
    from .response_node_js_session_response import ResponseNodeJsSessionResponse
    from .response_node_js_update_session_response import ResponseNodeJsUpdateSessionResponse
    from .response_observation_export_result import ResponseObservationExportResult
    from .response_observation_live_snapshot import ResponseObservationLiveSnapshot
    from .response_observation_report_info import ResponseObservationReportInfo
    from .response_observation_start_result import ResponseObservationStartResult
    from .response_observation_status import ResponseObservationStatus
    from .response_observation_stop_result import ResponseObservationStopResult
    from .response_proxy_diagnose_result import ResponseProxyDiagnoseResult
    from .response_proxy_health_check import ResponseProxyHealthCheck
    from .response_proxy_mapping_route import ResponseProxyMappingRoute
    from .response_proxy_upstream_info import ResponseProxyUpstreamInfo
    from .response_sandbox_hook import ResponseSandboxHook
    from .response_shell_command_result import ResponseShellCommandResult
    from .response_shell_create_session_response import ResponseShellCreateSessionResponse
    from .response_shell_kill_result import ResponseShellKillResult
    from .response_shell_session_stats import ResponseShellSessionStats
    from .response_shell_view_result import ResponseShellViewResult
    from .response_shell_wait_result import ResponseShellWaitResult
    from .response_shell_write_result import ResponseShellWriteResult
    from .response_skill_content_result import ResponseSkillContentResult
    from .response_skill_metadata import ResponseSkillMetadata
    from .response_skill_metadata_collection import ResponseSkillMetadataCollection
    from .response_skill_registration_result import ResponseSkillRegistrationResult
    from .response_str import ResponseStr
    from .response_union_file_find_result_file_operation_error import ResponseUnionFileFindResultFileOperationError
    from .response_union_file_find_result_file_operation_error_data import (
        ResponseUnionFileFindResultFileOperationErrorData,
    )
    from .response_union_file_glob_result_file_operation_error import ResponseUnionFileGlobResultFileOperationError
    from .response_union_file_glob_result_file_operation_error_data import (
        ResponseUnionFileGlobResultFileOperationErrorData,
    )
    from .response_union_file_grep_result_file_operation_error import ResponseUnionFileGrepResultFileOperationError
    from .response_union_file_grep_result_file_operation_error_data import (
        ResponseUnionFileGrepResultFileOperationErrorData,
    )
    from .response_union_file_list_result_file_operation_error import ResponseUnionFileListResultFileOperationError
    from .response_union_file_list_result_file_operation_error_data import (
        ResponseUnionFileListResultFileOperationErrorData,
    )
    from .response_union_file_read_result_file_operation_error import ResponseUnionFileReadResultFileOperationError
    from .response_union_file_read_result_file_operation_error_data import (
        ResponseUnionFileReadResultFileOperationErrorData,
    )
    from .response_union_file_replace_result_file_operation_error import (
        ResponseUnionFileReplaceResultFileOperationError,
    )
    from .response_union_file_replace_result_file_operation_error_data import (
        ResponseUnionFileReplaceResultFileOperationErrorData,
    )
    from .response_union_file_search_result_file_operation_error import ResponseUnionFileSearchResultFileOperationError
    from .response_union_file_search_result_file_operation_error_data import (
        ResponseUnionFileSearchResultFileOperationErrorData,
    )
    from .response_union_file_upload_result_file_operation_error import ResponseUnionFileUploadResultFileOperationError
    from .response_union_file_upload_result_file_operation_error_data import (
        ResponseUnionFileUploadResultFileOperationErrorData,
    )
    from .response_union_file_write_result_file_operation_error import ResponseUnionFileWriteResultFileOperationError
    from .response_union_file_write_result_file_operation_error_data import (
        ResponseUnionFileWriteResultFileOperationErrorData,
    )
    from .response_union_proxy_upstream_info_none_type import ResponseUnionProxyUpstreamInfoNoneType
    from .response_union_str_replace_editor_result_file_operation_error import (
        ResponseUnionStrReplaceEditorResultFileOperationError,
    )
    from .response_union_str_replace_editor_result_file_operation_error_data import (
        ResponseUnionStrReplaceEditorResultFileOperationErrorData,
    )
    from .restart_mode import RestartMode
    from .restart_request import RestartRequest
    from .right_click_action import RightClickAction
    from .route_response_model import RouteResponseModel
    from .runtime_env import RuntimeEnv
    from .sandbox_detail import SandboxDetail
    from .sandbox_hook import SandboxHook
    from .sandbox_response import SandboxResponse
    from .scroll_action import ScrollAction
    from .session_info import SessionInfo
    from .session_status import SessionStatus
    from .shell_command_result import ShellCommandResult
    from .shell_create_session_response import ShellCreateSessionResponse
    from .shell_kill_result import ShellKillResult
    from .shell_session_info import ShellSessionInfo
    from .shell_session_stats import ShellSessionStats
    from .shell_view_result import ShellViewResult
    from .shell_wait_result import ShellWaitResult
    from .shell_write_result import ShellWriteResult
    from .skill_content_result import SkillContentResult
    from .skill_metadata import SkillMetadata
    from .skill_metadata_collection import SkillMetadataCollection
    from .skill_registration_result import SkillRegistrationResult
    from .status import Status
    from .str_replace_editor_result import StrReplaceEditorResult
    from .system_env import SystemEnv
    from .text_content import TextContent
    from .text_resource_contents import TextResourceContents
    from .tool import Tool
    from .tool_annotations import ToolAnnotations
    from .tool_category import ToolCategory
    from .tool_execution import ToolExecution
    from .tool_execution_task_support import ToolExecutionTaskSupport
    from .tool_spec import ToolSpec
    from .typing_action import TypingAction
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .wait_action import WaitAction
_dynamic_imports: typing.Dict[str, str] = {
    "ActionData": ".action_data",
    "ActionResponse": ".action_response",
    "ActiveSessionsResult": ".active_sessions_result",
    "ActiveShellSessionsResult": ".active_shell_sessions_result",
    "Annotations": ".annotations",
    "AnnotationsAudienceItem": ".annotations_audience_item",
    "AudioContent": ".audio_content",
    "AvailableTool": ".available_tool",
    "BashCommandInfo": ".bash_command_info",
    "BashCommandStatus": ".bash_command_status",
    "BashExecResult": ".bash_exec_result",
    "BashOutputResult": ".bash_output_result",
    "BashSessionInfo": ".bash_session_info",
    "BlobResourceContents": ".blob_resource_contents",
    "BrowserInfoResult": ".browser_info_result",
    "BrowserViewport": ".browser_viewport",
    "Button": ".button",
    "CallToolResult": ".call_tool_result",
    "CaptchaWaitResult": ".captcha_wait_result",
    "CheckRequest": ".check_request",
    "ClickAction": ".click_action",
    "CodeExecuteResponse": ".code_execute_response",
    "CodeInfoResponse": ".code_info_response",
    "CodeLanguageInfo": ".code_language_info",
    "CommandStatus": ".command_status",
    "ConsoleRecord": ".console_record",
    "DependencyCommandResult": ".dependency_command_result",
    "DisplayRecordResult": ".display_record_result",
    "DoubleClickAction": ".double_click_action",
    "DragRelAction": ".drag_rel_action",
    "DragToAction": ".drag_to_action",
    "EmbeddedResource": ".embedded_resource",
    "FileContentEncoding": ".file_content_encoding",
    "FileDownloadChangePolicy": ".file_download_change_policy",
    "FileFindResult": ".file_find_result",
    "FileGlobResult": ".file_glob_result",
    "FileGrepResult": ".file_grep_result",
    "FileInfo": ".file_info",
    "FileListResult": ".file_list_result",
    "FileOperationError": ".file_operation_error",
    "FileReadResult": ".file_read_result",
    "FileReplaceResult": ".file_replace_result",
    "FileSearchResult": ".file_search_result",
    "FileUploadResult": ".file_upload_result",
    "FileWriteResult": ".file_write_result",
    "GlobFileInfo": ".glob_file_info",
    "GrepMatch": ".grep_match",
    "HotkeyAction": ".hotkey_action",
    "HttpValidationError": ".http_validation_error",
    "Icon": ".icon",
    "ImageContent": ".image_content",
    "JupyterCreateSessionResponse": ".jupyter_create_session_response",
    "JupyterExecuteResponse": ".jupyter_execute_response",
    "JupyterInfoResponse": ".jupyter_info_response",
    "JupyterOutput": ".jupyter_output",
    "KeyDownAction": ".key_down_action",
    "KeyUpAction": ".key_up_action",
    "Language": ".language",
    "ListToolsResult": ".list_tools_result",
    "MouseDownAction": ".mouse_down_action",
    "MouseUpAction": ".mouse_up_action",
    "MoveRelAction": ".move_rel_action",
    "MoveToAction": ".move_to_action",
    "NodeJsCreateSessionResponse": ".node_js_create_session_response",
    "NodeJsDeleteSessionResponse": ".node_js_delete_session_response",
    "NodeJsExecuteResponse": ".node_js_execute_response",
    "NodeJsOutput": ".node_js_output",
    "NodeJsPackageInfo": ".node_js_package_info",
    "NodeJsRuntimeInfo": ".node_js_runtime_info",
    "NodeJsSessionInfo": ".node_js_session_info",
    "NodeJsSessionListResponse": ".node_js_session_list_response",
    "NodeJsSessionResponse": ".node_js_session_response",
    "NodeJsUpdateSessionResponse": ".node_js_update_session_response",
    "ObservationCgroupSnapshot": ".observation_cgroup_snapshot",
    "ObservationDiskSnapshot": ".observation_disk_snapshot",
    "ObservationEvent": ".observation_event",
    "ObservationExportResult": ".observation_export_result",
    "ObservationLiveSnapshot": ".observation_live_snapshot",
    "ObservationMode": ".observation_mode",
    "ObservationProcessSnapshot": ".observation_process_snapshot",
    "ObservationReportInfo": ".observation_report_info",
    "ObservationStartResult": ".observation_start_result",
    "ObservationStatus": ".observation_status",
    "ObservationStopResult": ".observation_stop_result",
    "PressAction": ".press_action",
    "ProxyBypassRequest": ".proxy_bypass_request",
    "ProxyDiagnoseResult": ".proxy_diagnose_result",
    "ProxyHealthCheck": ".proxy_health_check",
    "ProxyMappingRoute": ".proxy_mapping_route",
    "ProxyUpstreamInfo": ".proxy_upstream_info",
    "Resolution": ".resolution",
    "Resource": ".resource",
    "ResourceLink": ".resource_link",
    "Response": ".response",
    "ResponseActiveSessionsResult": ".response_active_sessions_result",
    "ResponseActiveShellSessionsResult": ".response_active_shell_sessions_result",
    "ResponseBashExecResult": ".response_bash_exec_result",
    "ResponseBashOutputResult": ".response_bash_output_result",
    "ResponseBashSessionInfo": ".response_bash_session_info",
    "ResponseBrowserInfoResult": ".response_browser_info_result",
    "ResponseCallToolResultModel": ".response_call_tool_result_model",
    "ResponseCallToolResultModelDataContentItem": ".response_call_tool_result_model_data_content_item",
    "ResponseCallToolResultModelDataContentItem_Audio": ".response_call_tool_result_model_data_content_item",
    "ResponseCallToolResultModelDataContentItem_Image": ".response_call_tool_result_model_data_content_item",
    "ResponseCallToolResultModelDataContentItem_Resource": ".response_call_tool_result_model_data_content_item",
    "ResponseCallToolResultModelDataContentItem_ResourceLink": ".response_call_tool_result_model_data_content_item",
    "ResponseCallToolResultModelDataContentItem_Text": ".response_call_tool_result_model_data_content_item",
    "ResponseCaptchaWaitResult": ".response_captcha_wait_result",
    "ResponseCodeExecuteResponse": ".response_code_execute_response",
    "ResponseCodeInfoResponse": ".response_code_info_response",
    "ResponseDict": ".response_dict",
    "ResponseDisplayRecordResult": ".response_display_record_result",
    "ResponseJupyterCreateSessionResponse": ".response_jupyter_create_session_response",
    "ResponseJupyterExecuteResponse": ".response_jupyter_execute_response",
    "ResponseJupyterInfoResponse": ".response_jupyter_info_response",
    "ResponseList": ".response_list",
    "ResponseListBashSessionInfo": ".response_list_bash_session_info",
    "ResponseListObservationReportInfo": ".response_list_observation_report_info",
    "ResponseListProxyMappingRoute": ".response_list_proxy_mapping_route",
    "ResponseListSandboxHook": ".response_list_sandbox_hook",
    "ResponseListStr": ".response_list_str",
    "ResponseListToolsResultModel": ".response_list_tools_result_model",
    "ResponseNodeJsCreateSessionResponse": ".response_node_js_create_session_response",
    "ResponseNodeJsDeleteSessionResponse": ".response_node_js_delete_session_response",
    "ResponseNodeJsExecuteResponse": ".response_node_js_execute_response",
    "ResponseNodeJsRuntimeInfo": ".response_node_js_runtime_info",
    "ResponseNodeJsSessionListResponse": ".response_node_js_session_list_response",
    "ResponseNodeJsSessionResponse": ".response_node_js_session_response",
    "ResponseNodeJsUpdateSessionResponse": ".response_node_js_update_session_response",
    "ResponseObservationExportResult": ".response_observation_export_result",
    "ResponseObservationLiveSnapshot": ".response_observation_live_snapshot",
    "ResponseObservationReportInfo": ".response_observation_report_info",
    "ResponseObservationStartResult": ".response_observation_start_result",
    "ResponseObservationStatus": ".response_observation_status",
    "ResponseObservationStopResult": ".response_observation_stop_result",
    "ResponseProxyDiagnoseResult": ".response_proxy_diagnose_result",
    "ResponseProxyHealthCheck": ".response_proxy_health_check",
    "ResponseProxyMappingRoute": ".response_proxy_mapping_route",
    "ResponseProxyUpstreamInfo": ".response_proxy_upstream_info",
    "ResponseSandboxHook": ".response_sandbox_hook",
    "ResponseShellCommandResult": ".response_shell_command_result",
    "ResponseShellCreateSessionResponse": ".response_shell_create_session_response",
    "ResponseShellKillResult": ".response_shell_kill_result",
    "ResponseShellSessionStats": ".response_shell_session_stats",
    "ResponseShellViewResult": ".response_shell_view_result",
    "ResponseShellWaitResult": ".response_shell_wait_result",
    "ResponseShellWriteResult": ".response_shell_write_result",
    "ResponseSkillContentResult": ".response_skill_content_result",
    "ResponseSkillMetadata": ".response_skill_metadata",
    "ResponseSkillMetadataCollection": ".response_skill_metadata_collection",
    "ResponseSkillRegistrationResult": ".response_skill_registration_result",
    "ResponseStr": ".response_str",
    "ResponseUnionFileFindResultFileOperationError": ".response_union_file_find_result_file_operation_error",
    "ResponseUnionFileFindResultFileOperationErrorData": ".response_union_file_find_result_file_operation_error_data",
    "ResponseUnionFileGlobResultFileOperationError": ".response_union_file_glob_result_file_operation_error",
    "ResponseUnionFileGlobResultFileOperationErrorData": ".response_union_file_glob_result_file_operation_error_data",
    "ResponseUnionFileGrepResultFileOperationError": ".response_union_file_grep_result_file_operation_error",
    "ResponseUnionFileGrepResultFileOperationErrorData": ".response_union_file_grep_result_file_operation_error_data",
    "ResponseUnionFileListResultFileOperationError": ".response_union_file_list_result_file_operation_error",
    "ResponseUnionFileListResultFileOperationErrorData": ".response_union_file_list_result_file_operation_error_data",
    "ResponseUnionFileReadResultFileOperationError": ".response_union_file_read_result_file_operation_error",
    "ResponseUnionFileReadResultFileOperationErrorData": ".response_union_file_read_result_file_operation_error_data",
    "ResponseUnionFileReplaceResultFileOperationError": ".response_union_file_replace_result_file_operation_error",
    "ResponseUnionFileReplaceResultFileOperationErrorData": ".response_union_file_replace_result_file_operation_error_data",
    "ResponseUnionFileSearchResultFileOperationError": ".response_union_file_search_result_file_operation_error",
    "ResponseUnionFileSearchResultFileOperationErrorData": ".response_union_file_search_result_file_operation_error_data",
    "ResponseUnionFileUploadResultFileOperationError": ".response_union_file_upload_result_file_operation_error",
    "ResponseUnionFileUploadResultFileOperationErrorData": ".response_union_file_upload_result_file_operation_error_data",
    "ResponseUnionFileWriteResultFileOperationError": ".response_union_file_write_result_file_operation_error",
    "ResponseUnionFileWriteResultFileOperationErrorData": ".response_union_file_write_result_file_operation_error_data",
    "ResponseUnionProxyUpstreamInfoNoneType": ".response_union_proxy_upstream_info_none_type",
    "ResponseUnionStrReplaceEditorResultFileOperationError": ".response_union_str_replace_editor_result_file_operation_error",
    "ResponseUnionStrReplaceEditorResultFileOperationErrorData": ".response_union_str_replace_editor_result_file_operation_error_data",
    "RestartMode": ".restart_mode",
    "RestartRequest": ".restart_request",
    "RightClickAction": ".right_click_action",
    "RouteResponseModel": ".route_response_model",
    "RuntimeEnv": ".runtime_env",
    "SandboxDetail": ".sandbox_detail",
    "SandboxHook": ".sandbox_hook",
    "SandboxResponse": ".sandbox_response",
    "ScrollAction": ".scroll_action",
    "SessionInfo": ".session_info",
    "SessionStatus": ".session_status",
    "ShellCommandResult": ".shell_command_result",
    "ShellCreateSessionResponse": ".shell_create_session_response",
    "ShellKillResult": ".shell_kill_result",
    "ShellSessionInfo": ".shell_session_info",
    "ShellSessionStats": ".shell_session_stats",
    "ShellViewResult": ".shell_view_result",
    "ShellWaitResult": ".shell_wait_result",
    "ShellWriteResult": ".shell_write_result",
    "SkillContentResult": ".skill_content_result",
    "SkillMetadata": ".skill_metadata",
    "SkillMetadataCollection": ".skill_metadata_collection",
    "SkillRegistrationResult": ".skill_registration_result",
    "Status": ".status",
    "StrReplaceEditorResult": ".str_replace_editor_result",
    "SystemEnv": ".system_env",
    "TextContent": ".text_content",
    "TextResourceContents": ".text_resource_contents",
    "Tool": ".tool",
    "ToolAnnotations": ".tool_annotations",
    "ToolCategory": ".tool_category",
    "ToolExecution": ".tool_execution",
    "ToolExecutionTaskSupport": ".tool_execution_task_support",
    "ToolSpec": ".tool_spec",
    "TypingAction": ".typing_action",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "WaitAction": ".wait_action",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActionData",
    "ActionResponse",
    "ActiveSessionsResult",
    "ActiveShellSessionsResult",
    "Annotations",
    "AnnotationsAudienceItem",
    "AudioContent",
    "AvailableTool",
    "BashCommandInfo",
    "BashCommandStatus",
    "BashExecResult",
    "BashOutputResult",
    "BashSessionInfo",
    "BlobResourceContents",
    "BrowserInfoResult",
    "BrowserViewport",
    "Button",
    "CallToolResult",
    "CaptchaWaitResult",
    "CheckRequest",
    "ClickAction",
    "CodeExecuteResponse",
    "CodeInfoResponse",
    "CodeLanguageInfo",
    "CommandStatus",
    "ConsoleRecord",
    "DependencyCommandResult",
    "DisplayRecordResult",
    "DoubleClickAction",
    "DragRelAction",
    "DragToAction",
    "EmbeddedResource",
    "FileContentEncoding",
    "FileDownloadChangePolicy",
    "FileFindResult",
    "FileGlobResult",
    "FileGrepResult",
    "FileInfo",
    "FileListResult",
    "FileOperationError",
    "FileReadResult",
    "FileReplaceResult",
    "FileSearchResult",
    "FileUploadResult",
    "FileWriteResult",
    "GlobFileInfo",
    "GrepMatch",
    "HotkeyAction",
    "HttpValidationError",
    "Icon",
    "ImageContent",
    "JupyterCreateSessionResponse",
    "JupyterExecuteResponse",
    "JupyterInfoResponse",
    "JupyterOutput",
    "KeyDownAction",
    "KeyUpAction",
    "Language",
    "ListToolsResult",
    "MouseDownAction",
    "MouseUpAction",
    "MoveRelAction",
    "MoveToAction",
    "NodeJsCreateSessionResponse",
    "NodeJsDeleteSessionResponse",
    "NodeJsExecuteResponse",
    "NodeJsOutput",
    "NodeJsPackageInfo",
    "NodeJsRuntimeInfo",
    "NodeJsSessionInfo",
    "NodeJsSessionListResponse",
    "NodeJsSessionResponse",
    "NodeJsUpdateSessionResponse",
    "ObservationCgroupSnapshot",
    "ObservationDiskSnapshot",
    "ObservationEvent",
    "ObservationExportResult",
    "ObservationLiveSnapshot",
    "ObservationMode",
    "ObservationProcessSnapshot",
    "ObservationReportInfo",
    "ObservationStartResult",
    "ObservationStatus",
    "ObservationStopResult",
    "PressAction",
    "ProxyBypassRequest",
    "ProxyDiagnoseResult",
    "ProxyHealthCheck",
    "ProxyMappingRoute",
    "ProxyUpstreamInfo",
    "Resolution",
    "Resource",
    "ResourceLink",
    "Response",
    "ResponseActiveSessionsResult",
    "ResponseActiveShellSessionsResult",
    "ResponseBashExecResult",
    "ResponseBashOutputResult",
    "ResponseBashSessionInfo",
    "ResponseBrowserInfoResult",
    "ResponseCallToolResultModel",
    "ResponseCallToolResultModelDataContentItem",
    "ResponseCallToolResultModelDataContentItem_Audio",
    "ResponseCallToolResultModelDataContentItem_Image",
    "ResponseCallToolResultModelDataContentItem_Resource",
    "ResponseCallToolResultModelDataContentItem_ResourceLink",
    "ResponseCallToolResultModelDataContentItem_Text",
    "ResponseCaptchaWaitResult",
    "ResponseCodeExecuteResponse",
    "ResponseCodeInfoResponse",
    "ResponseDict",
    "ResponseDisplayRecordResult",
    "ResponseJupyterCreateSessionResponse",
    "ResponseJupyterExecuteResponse",
    "ResponseJupyterInfoResponse",
    "ResponseList",
    "ResponseListBashSessionInfo",
    "ResponseListObservationReportInfo",
    "ResponseListProxyMappingRoute",
    "ResponseListSandboxHook",
    "ResponseListStr",
    "ResponseListToolsResultModel",
    "ResponseNodeJsCreateSessionResponse",
    "ResponseNodeJsDeleteSessionResponse",
    "ResponseNodeJsExecuteResponse",
    "ResponseNodeJsRuntimeInfo",
    "ResponseNodeJsSessionListResponse",
    "ResponseNodeJsSessionResponse",
    "ResponseNodeJsUpdateSessionResponse",
    "ResponseObservationExportResult",
    "ResponseObservationLiveSnapshot",
    "ResponseObservationReportInfo",
    "ResponseObservationStartResult",
    "ResponseObservationStatus",
    "ResponseObservationStopResult",
    "ResponseProxyDiagnoseResult",
    "ResponseProxyHealthCheck",
    "ResponseProxyMappingRoute",
    "ResponseProxyUpstreamInfo",
    "ResponseSandboxHook",
    "ResponseShellCommandResult",
    "ResponseShellCreateSessionResponse",
    "ResponseShellKillResult",
    "ResponseShellSessionStats",
    "ResponseShellViewResult",
    "ResponseShellWaitResult",
    "ResponseShellWriteResult",
    "ResponseSkillContentResult",
    "ResponseSkillMetadata",
    "ResponseSkillMetadataCollection",
    "ResponseSkillRegistrationResult",
    "ResponseStr",
    "ResponseUnionFileFindResultFileOperationError",
    "ResponseUnionFileFindResultFileOperationErrorData",
    "ResponseUnionFileGlobResultFileOperationError",
    "ResponseUnionFileGlobResultFileOperationErrorData",
    "ResponseUnionFileGrepResultFileOperationError",
    "ResponseUnionFileGrepResultFileOperationErrorData",
    "ResponseUnionFileListResultFileOperationError",
    "ResponseUnionFileListResultFileOperationErrorData",
    "ResponseUnionFileReadResultFileOperationError",
    "ResponseUnionFileReadResultFileOperationErrorData",
    "ResponseUnionFileReplaceResultFileOperationError",
    "ResponseUnionFileReplaceResultFileOperationErrorData",
    "ResponseUnionFileSearchResultFileOperationError",
    "ResponseUnionFileSearchResultFileOperationErrorData",
    "ResponseUnionFileUploadResultFileOperationError",
    "ResponseUnionFileUploadResultFileOperationErrorData",
    "ResponseUnionFileWriteResultFileOperationError",
    "ResponseUnionFileWriteResultFileOperationErrorData",
    "ResponseUnionProxyUpstreamInfoNoneType",
    "ResponseUnionStrReplaceEditorResultFileOperationError",
    "ResponseUnionStrReplaceEditorResultFileOperationErrorData",
    "RestartMode",
    "RestartRequest",
    "RightClickAction",
    "RouteResponseModel",
    "RuntimeEnv",
    "SandboxDetail",
    "SandboxHook",
    "SandboxResponse",
    "ScrollAction",
    "SessionInfo",
    "SessionStatus",
    "ShellCommandResult",
    "ShellCreateSessionResponse",
    "ShellKillResult",
    "ShellSessionInfo",
    "ShellSessionStats",
    "ShellViewResult",
    "ShellWaitResult",
    "ShellWriteResult",
    "SkillContentResult",
    "SkillMetadata",
    "SkillMetadataCollection",
    "SkillRegistrationResult",
    "Status",
    "StrReplaceEditorResult",
    "SystemEnv",
    "TextContent",
    "TextResourceContents",
    "Tool",
    "ToolAnnotations",
    "ToolCategory",
    "ToolExecution",
    "ToolExecutionTaskSupport",
    "ToolSpec",
    "TypingAction",
    "ValidationError",
    "ValidationErrorLocItem",
    "WaitAction",
]
