# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FileOperationError(UniversalBaseModel):
    """
    Structured file-tool execution error.
    """

    path: str = pydantic.Field()
    """
    Path used for the file operation
    """

    operation: str = pydantic.Field()
    """
    File operation name
    """

    message: str = pydantic.Field()
    """
    Human-readable error message
    """

    error_type: str = pydantic.Field()
    """
    Normalized file error category
    """

    retryable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether retrying may succeed
    """

    errno: typing.Optional[int] = pydantic.Field(default=None)
    """
    Original OS errno when available
    """

    errno_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original OS errno symbolic name when available
    """

    exception_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original Python exception type when available
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
