# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ObservationDiskSnapshot(UniversalBaseModel):
    path: str
    used_bytes: int
    total_bytes: int
    free_bytes: int
    usage_pct: float
    inode_used: typing.Optional[int] = None
    inode_total: typing.Optional[int] = None
    inode_usage_pct: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
