# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .observation_mode import ObservationMode


class ObservationStatus(UniversalBaseModel):
    mode: ObservationMode
    running: bool
    session_id: typing.Optional[str] = None
    started_at: typing.Optional[dt.datetime] = None
    ends_at: typing.Optional[dt.datetime] = None
    interval_seconds: typing.Optional[float] = None
    last_sample_at: typing.Optional[dt.datetime] = None
    runtime_dir: typing.Optional[str] = None
    report_count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
