# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProxyHealthCheck(UniversalBaseModel):
    healthy: bool = pydantic.Field()
    """
    Overall health status
    """

    gost_alive: bool = pydantic.Field()
    """
    GOST proxy process is reachable via API
    """

    nginx_alive: bool = pydantic.Field()
    """
    nginx process is running
    """

    config_consistent: bool = pydantic.Field()
    """
    Domain sets in proxy-map.json, gost-hosts.txt, and nginx conf are consistent
    """

    inconsistencies: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of inconsistency details (empty when config_consistent is true)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
