# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProxyUpstreamInfo(UniversalBaseModel):
    addr: str = pydantic.Field()
    """
    Upstream proxy address (host:port)
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Proxy auth username (if authenticated)
    """

    password: typing.Optional[str] = pydantic.Field(default=None)
    """
    Proxy auth password (if authenticated)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
