// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace SandboxService {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SandboxService {
    protected readonly _options: SandboxService.Options;

    constructor(_options: SandboxService.Options) {
        this._options = _options;
    }

    /**
     * Get sandbox environment information
     *
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.getContext()
     */
    public getContext(
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.SandboxResponse, Sandbox.sandbox.getContext.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getContext(requestOptions));
    }

    private async __getContext(
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.SandboxResponse, Sandbox.sandbox.getContext.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.SandboxResponse,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.getContext.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Get installed Python packages
     *
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.getPythonPackages()
     */
    public getPythonPackages(
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.sandbox.getPythonPackages.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getPythonPackages(requestOptions));
    }

    private async __getPythonPackages(
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.sandbox.getPythonPackages.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/packages/python",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.getPythonPackages.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Get installed Node.js packages
     *
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.getNodejsPackages()
     */
    public getNodejsPackages(
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.sandbox.getNodejsPackages.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getNodejsPackages(requestOptions));
    }

    private async __getNodejsPackages(
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.sandbox.getNodejsPackages.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/packages/nodejs",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.getNodejsPackages.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * List registered lifecycle hooks, optionally filtered by event.
     *
     * @param {Sandbox.SandboxListHooksRequest} request
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.listHooks({
     *         event: "event"
     *     })
     */
    public listHooks(
        request: Sandbox.SandboxListHooksRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseListSandboxHook, Sandbox.sandbox.listHooks.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__listHooks(request, requestOptions));
    }

    private async __listHooks(
        request: Sandbox.SandboxListHooksRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseListSandboxHook, Sandbox.sandbox.listHooks.Error>>
    > {
        const { event } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (event != null) {
            _queryParams.event = event;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/hooks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseListSandboxHook,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.listHooks.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.listHooks.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Register a lifecycle hook. Currently supported events: shutdown.
     *
     * @param {Sandbox.RegisterHookRequest} request
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.registerHook({
     *         name: "name",
     *         command: "command"
     *     })
     */
    public registerHook(
        request: Sandbox.RegisterHookRequest,
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseSandboxHook, Sandbox.sandbox.registerHook.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__registerHook(request, requestOptions));
    }

    private async __registerHook(
        request: Sandbox.RegisterHookRequest,
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseSandboxHook, Sandbox.sandbox.registerHook.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/hooks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseSandboxHook,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.registerHook.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.registerHook.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Remove a hook by name. ENV hooks cannot be removed.
     *
     * @param {string} name
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.removeHook("name")
     */
    public removeHook(
        name: string,
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.sandbox.removeHook.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__removeHook(name, requestOptions));
    }

    private async __removeHook(
        name: string,
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.sandbox.removeHook.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/sandbox/hooks/${core.url.encodePathParam(name)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.removeHook.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.removeHook.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeStatus()
     */
    public observeStatus(
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseObservationStatus, Sandbox.sandbox.observeStatus.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeStatus(requestOptions));
    }

    private async __observeStatus(
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseObservationStatus, Sandbox.sandbox.observeStatus.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/observe/status",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseObservationStatus,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeStatus.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {Sandbox.SandboxObserveLiveRequest} request
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeLive({
     *         top_rows: 1
     *     })
     */
    public observeLive(
        request: Sandbox.SandboxObserveLiveRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseObservationLiveSnapshot, Sandbox.sandbox.observeLive.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeLive(request, requestOptions));
    }

    private async __observeLive(
        request: Sandbox.SandboxObserveLiveRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseObservationLiveSnapshot, Sandbox.sandbox.observeLive.Error>
        >
    > {
        const { top_rows: topRows } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (topRows != null) {
            _queryParams.top_rows = topRows.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/observe/live",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseObservationLiveSnapshot,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.observeLive.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeLive.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {Sandbox.ObserveStartRequest} request
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeStart()
     */
    public observeStart(
        request: Sandbox.ObserveStartRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseObservationStartResult, Sandbox.sandbox.observeStart.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeStart(request, requestOptions));
    }

    private async __observeStart(
        request: Sandbox.ObserveStartRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseObservationStartResult, Sandbox.sandbox.observeStart.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/observe/start",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseObservationStartResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.observeStart.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeStart.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {Sandbox.ObserveStopRequest} request
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeStop()
     */
    public observeStop(
        request: Sandbox.ObserveStopRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseObservationStopResult, Sandbox.sandbox.observeStop.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeStop(request, requestOptions));
    }

    private async __observeStop(
        request: Sandbox.ObserveStopRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseObservationStopResult, Sandbox.sandbox.observeStop.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/observe/stop",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseObservationStopResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.observeStop.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeStop.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {Sandbox.ObserveExportRequest} request
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeExport()
     */
    public observeExport(
        request: Sandbox.ObserveExportRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseObservationExportResult, Sandbox.sandbox.observeExport.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeExport(request, requestOptions));
    }

    private async __observeExport(
        request: Sandbox.ObserveExportRequest = {},
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseObservationExportResult, Sandbox.sandbox.observeExport.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/observe/export",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseObservationExportResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.observeExport.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeExport.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeReports()
     */
    public observeReports(
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseListObservationReportInfo, Sandbox.sandbox.observeReports.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeReports(requestOptions));
    }

    private async __observeReports(
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseListObservationReportInfo, Sandbox.sandbox.observeReports.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/sandbox/observe/reports",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseListObservationReportInfo,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeReports.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    public observeReportDownload(
        reportId: string,
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<core.BinaryResponse, Sandbox.sandbox.observeReportDownload.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__observeReportDownload(reportId, requestOptions));
    }

    private async __observeReportDownload(
        reportId: string,
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<core.BinaryResponse, Sandbox.sandbox.observeReportDownload.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/sandbox/observe/reports/${core.url.encodePathParam(reportId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.observeReportDownload.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeReportDownload.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {string} reportId
     * @param {SandboxService.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.sandbox.observeReportDelete("report_id")
     */
    public observeReportDelete(
        reportId: string,
        requestOptions?: SandboxService.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseObservationReportInfo, Sandbox.sandbox.observeReportDelete.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__observeReportDelete(reportId, requestOptions));
    }

    private async __observeReportDelete(
        reportId: string,
        requestOptions?: SandboxService.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseObservationReportInfo, Sandbox.sandbox.observeReportDelete.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/sandbox/observe/reports/${core.url.encodePathParam(reportId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseObservationReportInfo,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.sandbox.observeReportDelete.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.sandbox.observeReportDelete.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
