// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BrowserPageScreenshotRequest {
    full_page?: boolean;
    format?: string;
    quality?: number;
}
