// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         expression: "expression"
 *     }
 */
export interface EvaluateRequest {
    expression: string;
}
