// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         save_path: "save_path"
 *     }
 */
export interface ExportConsoleLogsRequest {
    save_path: string;
    clear?: boolean;
}
