// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface NavigateRequest {
    url: string;
    wait_until?: Sandbox.NavigateRequestWaitUntil;
    timeout?: number;
}
