// This file was auto-generated by Fern from our API Definition.

export const AnnotationsAudienceItem = {
    User: "user",
    Assistant: "assistant",
} as const;
export type AnnotationsAudienceItem = (typeof AnnotationsAudienceItem)[keyof typeof AnnotationsAudienceItem];
