// This file was auto-generated by Fern from our API Definition.

/**
 * Describe an available command-line tool.
 */
export interface AvailableTool {
    /** Tool’s command / binary name */
    name: string;
    /** Tool’s functionality description */
    description?: string;
}
