// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Result of exec_command — returned by POST /v1/bash/exec.
 */
export interface BashExecResult {
    /** Session identifier */
    session_id: string;
    /** Unique command identifier */
    command_id: string;
    /** The executed command */
    command: string;
    /** Command execution status. Possible values: `pending` (accepted but not started yet; typically internal-only), `running` (still executing), `completed` (process exited and `exit_code` is available; a non-zero shell exit code still uses `completed`), `timed_out` (process was force-killed after `hard_timeout`), `killed` (process was terminated by kill/cleanup or an internal execution failure). */
    status: Sandbox.CommandStatus;
    /** Stdout output up to this point */
    stdout?: string;
    /** Stderr output up to this point */
    stderr?: string;
    /** Exit code (when completed) */
    exit_code?: number;
    /** Current stdout offset for subsequent /output calls */
    offset?: number;
    /** Current stderr offset */
    stderr_offset?: number;
}
