// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Result of get_output — returned by POST /v1/bash/output.
 */
export interface BashOutputResult {
    /** Session identifier */
    session_id: string;
    /** New stdout data since last offset */
    stdout?: string;
    /** New stderr data since last offset */
    stderr?: string;
    /** Current stdout offset (use for next request) */
    offset?: number;
    /** Current stderr offset (use for next request) */
    stderr_offset?: number;
    /** Current or most recent command status */
    command?: Sandbox.BashCommandInfo;
}
