// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Browser Info result
 */
export interface BrowserInfoResult {
    /** User agent */
    user_agent: string;
    /** Browser CDP URL */
    cdp_url: string;
    /** VNC URL */
    vnc_url: string;
    /** CDP UI URL (browser-ui) */
    cdp_ui_url?: string;
    /** Display size (from xrandr / env vars) */
    viewport: Sandbox.BrowserViewport;
    /** Actual Chrome page viewport (window.innerWidth/Height via CDP). Smaller than viewport because Chrome UI chrome takes space. */
    page_viewport?: Sandbox.BrowserViewport;
}
