// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ClickAction {
    x?: number;
    y?: number;
    button?: Sandbox.Button;
    num_clicks?: number;
}
