// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Unified code information response
 */
export interface CodeInfoResponse {
    /** List of supported languages and metadata */
    languages: Sandbox.CodeLanguageInfo[];
}
