// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Unified code execution response model
 */
export interface CodeExecuteResponse {
    /** Runtime language that executed the code */
    language: Sandbox.Language;
    /** Execution status indicator */
    status: string;
    /** Structured execution outputs */
    outputs?: Record<string, unknown>[];
    /** Echo of executed code */
    code: string;
    /** Captured standard output stream */
    stdout?: string;
    /** Captured standard error stream */
    stderr?: string;
    /** Process exit code when applicable */
    exit_code?: number;
    /** Captured error traceback lines when available */
    traceback?: string[];
    /** Session ID for stateful execution (only present when stateful=True) */
    session_id?: string;
}
