// This file was auto-generated by Fern from our API Definition.

/**
 * Shell command console record model
 */
export interface ConsoleRecord {
    /** Command prompt */
    ps1: string;
    /** Executed command */
    command: string;
    /** Command output */
    output?: string;
}
