// This file was auto-generated by Fern from our API Definition.

export interface DependencyCommandResult {
    /** Executed dependency command */
    command: string[];
    /** Whether the command succeeded */
    success: boolean;
    /** Standard output from command */
    stdout?: string;
    /** Standard error from command */
    stderr?: string;
}
