// This file was auto-generated by Fern from our API Definition.

export interface DragRelAction {
    /** Relative current position x-axis drag movement */
    x_offset: number;
    /** Relative current position y-axis drag movement */
    y_offset: number;
}
