// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * The contents of a resource, embedded into a prompt or tool call result.
 *
 * It is up to the client how best to render embedded resources for the benefit
 * of the LLM and/or the user.
 */
export interface EmbeddedResource {
    resource: Sandbox.Resource;
    annotations?: Sandbox.Annotations;
    _meta?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
