// This file was auto-generated by Fern from our API Definition.

/**
 * File read result
 */
export interface FileReadResult {
    /** File content */
    content: string;
    /** Path of the read file */
    file: string;
}
