// This file was auto-generated by Fern from our API Definition.

/**
 * File content search result
 */
export interface FileSearchResult {
    /** Path of the searched file */
    file: string;
    /** List of matched content */
    matches?: string[];
    /** List of matched line numbers */
    line_numbers?: number[];
}
