// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Multi-file grep result
 */
export interface FileGrepResult {
    /** Search directory path */
    path: string;
    /** Search pattern used */
    pattern: string;
    /** List of matches */
    matches?: Sandbox.GrepMatch[];
    /** Total number of matches */
    match_count?: number;
    /** Number of files searched */
    files_searched?: number;
    /** Number of files with matches */
    files_matched?: number;
    /** Whether results were truncated */
    truncated?: boolean;
}
