// This file was auto-generated by Fern from our API Definition.

/**
 * Single grep match
 */
export interface GrepMatch {
    /** File path containing the match */
    file: string;
    /** Line number (1-based) */
    line_number: number;
    /** Content of the matched line */
    line_content: string;
    /** Lines before the match */
    context_before?: string[];
    /** Lines after the match */
    context_after?: string[];
}
