// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Image content for a message.
 */
export interface ImageContent {
    data: string;
    mimeType: string;
    annotations?: Sandbox.Annotations;
    _meta?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
