// This file was auto-generated by Fern from our API Definition.

/**
 * Jupyter execution output model
 */
export interface JupyterOutput {
    /** Type of output: stream, execute_result, display_data, or error */
    output_type: string;
    /** Stream name (stdout/stderr) for stream outputs */
    name?: string;
    /** Text content for stream outputs */
    text?: string;
    /** Output data for execute_result/display_data */
    data?: Record<string, unknown>;
    /** Output metadata */
    metadata?: Record<string, unknown>;
    /** Execution count for execute_result */
    execution_count?: number;
    /** Error name for error outputs */
    ename?: string;
    /** Error value for error outputs */
    evalue?: string;
    /** Error traceback for error outputs */
    traceback?: string[];
}
