// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * The server's response to a tools/list request from the client.
 */
export interface ListToolsResult {
    _meta?: Record<string, unknown>;
    nextCursor?: string;
    tools: Sandbox.Tool[];
    /** Accepts any additional properties */
    [key: string]: any;
}
