// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface NodeJsExecuteResponse {
    /** Language that was executed (always 'javascript') */
    language: "javascript";
    /** Execution status: ok, error, or timeout */
    status: string;
    /** Execution count */
    execution_count?: number;
    /** List of execution outputs */
    outputs?: Sandbox.NodeJsOutput[];
    /** Code that was executed */
    code: string;
    /** Standard output */
    stdout?: string;
    /** Standard error */
    stderr?: string;
    /** Process exit code */
    exit_code: number;
    /** Session ID for stateful execution (use this to continue the session) */
    session_id?: string;
}
