// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface NodeJsCreateSessionResponse {
    /** Session ID */
    session_id: string;
    /** Whether the session was newly created */
    created: boolean;
    /** Additional message (e.g., if session already exists) */
    message?: string;
    /** Session information (if created) */
    session?: Sandbox.NodeJsSessionInfo;
}
