// This file was auto-generated by Fern from our API Definition.

export interface NodeJsSessionInfo {
    /** Session ID */
    session_id: string;
    /** Working directory */
    cwd: string;
    /** Session creation timestamp (ms since epoch) */
    created_at: number;
    /** Last activity timestamp (ms since epoch) */
    last_used: number;
    /** Maximum idle time in milliseconds */
    max_idle_time: number;
    /** Seconds since last activity */
    age_seconds: number;
    /** Session state: IDLE or EXECUTING */
    state: string;
}
