// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface NodeJsSessionListResponse {
    /** Map of session ID to session info */
    sessions?: Record<string, Sandbox.NodeJsSessionInfo>;
}
