// This file was auto-generated by Fern from our API Definition.

export interface NodeJsOutput {
    /** Type of output: stream, error, or execute_result */
    output_type: string;
    /** Stream name (stdout/stderr) for stream outputs */
    name?: string;
    /** Text content for stream outputs */
    text?: string;
    /** Error name for error outputs */
    ename?: string;
    /** Error value for error outputs */
    evalue?: string;
    /** Error traceback for error outputs */
    traceback?: string[];
    /** Data for execute_result outputs */
    data?: Record<string, unknown>;
    /** Metadata for outputs */
    metadata?: Record<string, unknown>;
}
