// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * NodeJS runtime information model
 */
export interface NodeJsRuntimeInfo {
    /** Node.js version */
    node_version: string;
    /** npm version */
    npm_version: string;
    /** List of supported languages */
    supported_languages: string[];
    /** Service description */
    description: string;
    /** Runtime directory path */
    runtime_directory?: string;
    /** Global npm directory path */
    global_npm_directory?: string;
    /** Pre-installed runtime packages */
    runtime_packages?: Sandbox.NodeJsPackageInfo[];
    /** Globally installed npm packages */
    global_packages?: Sandbox.NodeJsPackageInfo[];
    /** Error message if runtime info retrieval failed */
    error?: string;
    /** Available Node.js versions (e.g., node20, node22, node24) */
    available_versions?: string[];
    /** Currently active Node.js version */
    current_version?: string;
}
