// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ObservationLiveSnapshot {
    captured_at: string;
    mode: Sandbox.ObservationMode;
    cgroup: Sandbox.ObservationCgroupSnapshot;
    disk?: Sandbox.ObservationDiskSnapshot[];
    top_processes?: Sandbox.ObservationProcessSnapshot[];
    recent_events?: Sandbox.ObservationEvent[];
}
