// This file was auto-generated by Fern from our API Definition.

export interface ObservationDiskSnapshot {
    path: string;
    used_bytes: number;
    total_bytes: number;
    free_bytes: number;
    usage_pct: number;
    inode_used?: number;
    inode_total?: number;
    inode_usage_pct?: number;
}
