// This file was auto-generated by Fern from our API Definition.

export const ObservationMode = {
    Off: "off",
    Guardrail: "guardrail",
    Capture: "capture",
} as const;
export type ObservationMode = (typeof ObservationMode)[keyof typeof ObservationMode];
