// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ObservationStartResult {
    session_id: string;
    mode: Sandbox.ObservationMode;
    started_at: string;
    ends_at?: string;
    interval_seconds: number;
    runtime_dir: string;
}
