// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ProxyDiagnoseResult {
    url: string;
    matched_mapping?: Sandbox.ProxyMappingRoute;
    resolved_target?: string;
    target_reachable?: boolean;
    route: string;
}
