// This file was auto-generated by Fern from our API Definition.

export interface ProxyHealthCheck {
    /** Overall health status */
    healthy: boolean;
    /** GOST proxy process is reachable via API */
    gost_alive: boolean;
    /** nginx process is running */
    nginx_alive: boolean;
    /** Domain sets in proxy-map.json, gost-hosts.txt, and nginx conf are consistent */
    config_consistent: boolean;
    /** List of inconsistency details (empty when config_consistent is true) */
    inconsistencies?: string[];
}
