// This file was auto-generated by Fern from our API Definition.

export interface Resolution {
    /** Screen width in pixels. */
    width: number;
    /** Screen height in pixels. */
    height: number;
}
