// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ResponseSkillContentResult {
    /** Whether the operation was successful */
    success?: boolean;
    /** Operation result message */
    message?: string;
    /** Data returned from the operation */
    data?: Sandbox.SkillContentResult;
    /** Context hint for AI agents (e.g. tab changes) */
    hint?: string;
}
