// This file was auto-generated by Fern from our API Definition.

export interface ResponseStr {
    /** Whether the operation was successful */
    success?: boolean;
    /** Operation result message */
    message?: string;
    /** Data returned from the operation */
    data?: string;
    /** Context hint for AI agents (e.g. tab changes) */
    hint?: string;
}
