// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * system environment info
 */
export interface SandboxDetail {
    system: Sandbox.SystemEnv;
    runtime: Sandbox.RuntimeEnv;
    utils: Sandbox.ToolCategory[];
}
