// This file was auto-generated by Fern from our API Definition.

/**
 * Shell session information
 */
export interface ShellSessionInfo {
    /** Working directory */
    working_dir: string;
    /** Creation timestamp */
    created_at: string;
    /** Last used timestamp */
    last_used_at: string;
    /** Age of session in seconds */
    age_seconds: number;
    /** Session status */
    status: string;
    /** Currently executing command */
    current_command?: string;
}
