// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Process termination result model
 */
export interface ShellKillResult {
    /** Process status */
    status: Sandbox.BashCommandStatus;
    /** Process exit code before termination, None if process was still running */
    exit_code?: number;
    /** Deprecated: use exit_code instead. Kept for backward compatibility. */
    returncode?: number;
}
