// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Process input write result model
 */
export interface ShellWriteResult {
    /** Write status */
    status: Sandbox.BashCommandStatus;
}
