// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Shell session content view result model
 */
export interface ShellViewResult {
    /** Shell session output content */
    output: string;
    /** Shell session ID */
    session_id: string;
    /** Console command records */
    console?: Sandbox.ConsoleRecord[];
    /** Shell session status */
    status: Sandbox.BashCommandStatus;
    /** Last executed or currently executing command */
    command?: string;
    /** Command execution exit code, only has value when status is completed */
    exit_code?: number;
}
