// This file was auto-generated by Fern from our API Definition.

/**
 * Shell session statistics model
 */
export interface ShellSessionStats {
    /** Total number of sessions */
    total_sessions: number;
    /** Number of active sessions (used within last 5 minutes) */
    active_sessions: number;
    /** Number of idle sessions */
    idle_sessions: number;
    /** Maximum allowed sessions */
    max_sessions: number;
    /** Session timeout in seconds */
    session_timeout: number;
    /** Session usage ratio (0.0 to 1.0) */
    usage_ratio: number;
}
