// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Shell command execution result model
 */
export interface ShellCommandResult {
    /** Shell session ID */
    session_id: string;
    /** Executed command */
    command: string;
    /** Command execution status */
    status: Sandbox.BashCommandStatus;
    /** Command execution output, only has value when status is completed */
    output?: string;
    /** Console command records */
    console?: Sandbox.ConsoleRecord[];
    /** Command execution exit code, only has value when status is completed */
    exit_code?: number;
}
