// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface SkillRegistrationResult {
    /** Number of registered skills */
    count: number;
    /** Registered skills and metadata */
    registered?: Sandbox.SkillMetadata[];
}
