// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface SkillMetadataCollection {
    /** Collection of skill metadata entries */
    skills?: Sandbox.SkillMetadata[];
}
