// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface SkillMetadata {
    /** Skill name */
    name: string;
    /** Absolute path to the skill directory */
    path: string;
    /** Metadata parsed from SKILL.md front matter */
    metadata?: Record<string, unknown>;
    /** Dependency commands for the skill */
    dependency_commands?: Sandbox.DependencyCommandResult[];
}
