// This file was auto-generated by Fern from our API Definition.

export const Status = {
    Idle: "idle",
    Recording: "recording",
    Stopped: "stopped",
} as const;
export type Status = (typeof Status)[keyof typeof Status];
