// This file was auto-generated by Fern from our API Definition.

/**
 * String replace editor result based on openhands_aci CLIResult
 */
export interface StrReplaceEditorResult {
    /** Command execution output */
    output: string;
    /** Error message if any */
    error?: string;
    /** File path that was operated on */
    path: string;
    /** Whether the file existed before operation */
    prev_exist: boolean;
    /** Previous file content */
    old_content?: string;
    /** New file content after operation */
    new_content?: string;
    /** File metadata (only returned when enable_metadata=true for binary files) */
    metadata?: Record<string, unknown>;
}
