// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Text content for a message.
 */
export interface TextContent {
    text: string;
    annotations?: Sandbox.Annotations;
    _meta?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
