// This file was auto-generated by Fern from our API Definition.

/**
 * Text contents of a resource.
 */
export interface TextResourceContents {
    uri: string;
    mimeType?: string;
    _meta?: Record<string, unknown>;
    text: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
