// This file was auto-generated by Fern from our API Definition.

export interface TypingAction {
    text: string;
    /** Use clipboard for better character support (recommended for special/ASCII characters) */
    use_clipboard?: boolean;
}
