// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cookies: [{
 *                 "key": "value"
 *             }]
 *     }
 */
export interface CookieSetRequest {
    cookies: Record<string, unknown>[];
}
