// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         include_hidden: true
 *     }
 */
export interface ListMcpServersV1McpServersGetRequest {
    /** Whether to include hidden MCP servers in the response */
    include_hidden?: boolean;
}
