# This file was auto-generated by Fern from our API Definition.

import typing
from abc import ABC, abstractmethod


class BaseProvider(ABC):
    """
    Base class for cloud provider implementations.

    All cloud providers should inherit from this class and implement the
    required sandbox management methods.
    """

    @abstractmethod
    def create_sandbox(self, function_id: str, **kwargs: typing.Any) -> typing.Any:
        """
        Create a new sandbox instance.
        """
        pass

    @abstractmethod
    def delete_sandbox(
        self, function_id: str, sandbox_id: str, **kwargs: typing.Any
    ) -> typing.Any:
        """
        Delete an existing sandbox instance.
        """
        pass

    @abstractmethod
    def get_sandbox(
        self, function_id: str, sandbox_id: str, **kwargs: typing.Any
    ) -> typing.Any:
        """
        Get details of an existing sandbox instance.
        """
        pass

    @abstractmethod
    def list_sandboxes(self, function_id: str, **kwargs: typing.Any) -> typing.Any:
        """
        List all sandbox instances for a function.
        """
        pass
