// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace BrowserCaptcha {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BrowserCaptcha {
    protected readonly _options: BrowserCaptcha.Options;

    constructor(_options: BrowserCaptcha.Options) {
        this._options = _options;
    }

    /**
     * Detect CAPTCHA on the current page.
     *
     * @param {BrowserCaptcha.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browserCaptcha.detect()
     */
    public detect(
        requestOptions?: BrowserCaptcha.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.browserCaptcha.detect.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__detect(requestOptions));
    }

    private async __detect(
        requestOptions?: BrowserCaptcha.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.browserCaptcha.detect.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/captcha/detect",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browserCaptcha.detect.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Wait for CAPTCHA to be resolved.
     *
     * @param {Sandbox.CaptchaWaitRequest} request
     * @param {BrowserCaptcha.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browserCaptcha.wait()
     */
    public wait(
        request: Sandbox.CaptchaWaitRequest = {},
        requestOptions?: BrowserCaptcha.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseCaptchaWaitResult, Sandbox.browserCaptcha.wait.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__wait(request, requestOptions));
    }

    private async __wait(
        request: Sandbox.CaptchaWaitRequest = {},
        requestOptions?: BrowserCaptcha.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseCaptchaWaitResult, Sandbox.browserCaptcha.wait.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/captcha/wait",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseCaptchaWaitResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browserCaptcha.wait.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browserCaptcha.wait.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
