// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "path"
 *     }
 */
export interface CreateWatchRequest {
    /** Path of the file or directory to watch */
    path: string;
    /** Whether to recursively watch subdirectories */
    recursive?: boolean;
    /** Directory or glob patterns to exclude */
    exclude?: string[];
    /** Debounce window in milliseconds */
    debounce?: number;
    /** Glob filters; empty means all events are included */
    include_patterns?: string[];
}
