// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {
 *         file: "file",
 *         content: "content"
 *     }
 */
export interface FileWriteRequest {
    /** Absolute file path */
    file: string;
    /** Content to write (text or base64 encoded for binary) */
    content: string;
    /** Content encoding: utf-8 for text, base64 for binary data */
    encoding?: Sandbox.FileContentEncoding;
    /** Whether to use append mode */
    append?: boolean;
    /** Whether to add leading newline (only for text mode) */
    leading_newline?: boolean;
    /** Whether to add trailing newline (only for text mode) */
    trailing_newline?: boolean;
    /** Whether to use sudo privileges */
    sudo?: boolean;
}
