// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {
 *         path: "path"
 *     }
 */
export interface FileDownloadFileRequest {
    path: string;
    change_policy?: Sandbox.FileDownloadChangePolicy;
}
