// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "path",
 *         glob: "glob"
 *     }
 */
export interface FileFindRequest {
    /** Directory path to search */
    path: string;
    /** Filename pattern (glob syntax) */
    glob: string;
}
