// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file: "file",
 *         regex: "regex"
 *     }
 */
export interface FileSearchRequest {
    /** Absolute file path */
    file: string;
    /** Regular expression pattern */
    regex: string;
    /** Whether to use sudo privileges */
    sudo?: boolean;
}
