// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file: "file"
 *     }
 */
export interface FileReadRequest {
    /** Absolute file path */
    file: string;
    /** Start line (0-based) */
    start_line?: number;
    /** End line (not inclusive) */
    end_line?: number;
    /** Whether to use sudo privileges */
    sudo?: boolean;
}
