// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file: "file",
 *         old_str: "old_str",
 *         new_str: "new_str"
 *     }
 */
export interface FileReplaceRequest {
    /** Absolute file path */
    file: string;
    /** Original string to replace */
    old_str: string;
    /** New string to replace with */
    new_str: string;
    /** Whether to use sudo privileges */
    sudo?: boolean;
}
