// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PollRequest {
    /** Cursor returned by the previous call; only events with seq > cursor are returned */
    cursor?: number;
    /** Maximum number of events to return */
    limit?: number;
    /** Long-poll wait time in seconds; 0 returns immediately */
    timeout?: number;
}
