// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ObserveStopRequest {
    /** Optional active session id to stop */
    session_id?: string;
}
