// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         filter: "filter",
 *         limit: 1
 *     }
 */
export interface BrowserNetworkGetRequestsRequest {
    filter?: string;
    limit?: number;
}
