// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ShellKillProcessRequest {
    /** Unique identifier of the target shell session */
    id: string;
}
