// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         input: "input",
 *         press_enter: true
 *     }
 */
export interface ShellWriteToProcessRequest {
    /** Unique identifier of the target shell session */
    id: string;
    /** Input content to write to the process */
    input: string;
    /** Whether to press enter key after input */
    press_enter: boolean;
}
