// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ShellWaitRequest {
    /** Unique identifier of the target shell session */
    id: string;
    /** Wait time (seconds) */
    seconds?: number;
    /** Maximum wait time (seconds) for the command to complete */
    max_wait_seconds?: number;
}
