// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version: "version"
 *     }
 */
export interface NodejsDeleteSessionRequest {
    /** Node.js version to target: "node20", "node22", "node24", or aliases "20", "22", "24" */
    version?: string;
}
