// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         server: "proxy.example.com:3128"
 *     }
 */
export interface ProxyUpstreamUpdateRequest {
    /** Upstream proxy server. Supports plain host:port or user:pass@host:port */
    server: string;
    /** Optional shell command to obtain proxy credentials. The command stdout should be "username:password". When set, the result is injected into the server URL, replacing any inline credentials. */
    auth_cmd?: string;
}
