// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         source: "myapp.com",
 *         target: ":3000"
 *     }
 */
export interface ProxyMappingAddRequest {
    /** Source pattern: [protocol://]host[:port][/path], supports wildcard * */
    source: string;
    /** Target address: [host:]port[/path]. Host defaults to 127.0.0.1 */
    target: string;
}
