// This file was auto-generated by Fern from our API Definition.

import { Auth } from "./api/resources/auth/client/Client.js";
import { Bash } from "./api/resources/bash/client/Client.js";
import { Browser } from "./api/resources/browser/client/Client.js";
import { BrowserCaptcha } from "./api/resources/browserCaptcha/client/Client.js";
import { BrowserCookies } from "./api/resources/browserCookies/client/Client.js";
import { BrowserNetwork } from "./api/resources/browserNetwork/client/Client.js";
import { BrowserPage } from "./api/resources/browserPage/client/Client.js";
import { BrowserState } from "./api/resources/browserState/client/Client.js";
import { BrowserTabs } from "./api/resources/browserTabs/client/Client.js";
import { Code } from "./api/resources/code/client/Client.js";
import { Display } from "./api/resources/display/client/Client.js";
import { File_ } from "./api/resources/file/client/Client.js";
import { Jupyter } from "./api/resources/jupyter/client/Client.js";
import { Mcp } from "./api/resources/mcp/client/Client.js";
import { Nodejs } from "./api/resources/nodejs/client/Client.js";
import { Proxy } from "./api/resources/proxy/client/Client.js";
import { SandboxService } from "./api/resources/sandbox/client/Client.js";
import { Shell } from "./api/resources/shell/client/Client.js";
import { Skills } from "./api/resources/skills/client/Client.js";
import { Util } from "./api/resources/util/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace SandboxClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SandboxClient {
    protected readonly _options: SandboxClient.Options;
    protected _sandbox: SandboxService | undefined;
    protected _shell: Shell | undefined;
    protected _bash: Bash | undefined;
    protected _file: File_ | undefined;
    protected _jupyter: Jupyter | undefined;
    protected _nodejs: Nodejs | undefined;
    protected _mcp: Mcp | undefined;
    protected _browser: Browser | undefined;
    protected _browserPage: BrowserPage | undefined;
    protected _browserTabs: BrowserTabs | undefined;
    protected _browserCookies: BrowserCookies | undefined;
    protected _browserState: BrowserState | undefined;
    protected _browserNetwork: BrowserNetwork | undefined;
    protected _browserCaptcha: BrowserCaptcha | undefined;
    protected _code: Code | undefined;
    protected _util: Util | undefined;
    protected _skills: Skills | undefined;
    protected _proxy: Proxy | undefined;
    protected _display: Display | undefined;
    protected _auth: Auth | undefined;

    constructor(_options: SandboxClient.Options) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get sandbox(): SandboxService {
        return (this._sandbox ??= new SandboxService(this._options));
    }

    public get shell(): Shell {
        return (this._shell ??= new Shell(this._options));
    }

    public get bash(): Bash {
        return (this._bash ??= new Bash(this._options));
    }

    public get file(): File_ {
        return (this._file ??= new File_(this._options));
    }

    public get jupyter(): Jupyter {
        return (this._jupyter ??= new Jupyter(this._options));
    }

    public get nodejs(): Nodejs {
        return (this._nodejs ??= new Nodejs(this._options));
    }

    public get mcp(): Mcp {
        return (this._mcp ??= new Mcp(this._options));
    }

    public get browser(): Browser {
        return (this._browser ??= new Browser(this._options));
    }

    public get browserPage(): BrowserPage {
        return (this._browserPage ??= new BrowserPage(this._options));
    }

    public get browserTabs(): BrowserTabs {
        return (this._browserTabs ??= new BrowserTabs(this._options));
    }

    public get browserCookies(): BrowserCookies {
        return (this._browserCookies ??= new BrowserCookies(this._options));
    }

    public get browserState(): BrowserState {
        return (this._browserState ??= new BrowserState(this._options));
    }

    public get browserNetwork(): BrowserNetwork {
        return (this._browserNetwork ??= new BrowserNetwork(this._options));
    }

    public get browserCaptcha(): BrowserCaptcha {
        return (this._browserCaptcha ??= new BrowserCaptcha(this._options));
    }

    public get code(): Code {
        return (this._code ??= new Code(this._options));
    }

    public get util(): Util {
        return (this._util ??= new Util(this._options));
    }

    public get skills(): Skills {
        return (this._skills ??= new Skills(this._options));
    }

    public get proxy(): Proxy {
        return (this._proxy ??= new Proxy(this._options));
    }

    public get display(): Display {
        return (this._display ??= new Display(this._options));
    }

    public get auth(): Auth {
        return (this._auth ??= new Auth(this._options));
    }
}
