// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Shell {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Shell {
    protected readonly _options: Shell.Options;

    constructor(_options: Shell.Options) {
        this._options = _options;
    }

    /**
     * Execute command in the specified shell session
     * Supports SSE streaming if Accept header contains 'text/event-stream'
     *
     * @param {Sandbox.ShellExecRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.execCommand({
     *         command: "command"
     *     })
     */
    public execCommand(
        request: Sandbox.ShellExecRequest,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseShellCommandResult, Sandbox.shell.execCommand.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__execCommand(request, requestOptions));
    }

    private async __execCommand(
        request: Sandbox.ShellExecRequest,
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseShellCommandResult, Sandbox.shell.execCommand.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/exec",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellCommandResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.execCommand.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.execCommand.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * View output of the specified shell session
     * Supports SSE streaming if Accept header contains 'text/event-stream'
     *
     * @param {Sandbox.ShellViewRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.view({
     *         id: "id"
     *     })
     */
    public view(
        request: Sandbox.ShellViewRequest,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseShellViewResult, Sandbox.shell.view.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__view(request, requestOptions));
    }

    private async __view(
        request: Sandbox.ShellViewRequest,
        requestOptions?: Shell.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseShellViewResult, Sandbox.shell.view.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/view",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellViewResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.view.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.view.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Wait for the process in the specified shell session to return
     *
     * @param {Sandbox.ShellWaitRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.waitForProcess({
     *         id: "id"
     *     })
     */
    public waitForProcess(
        request: Sandbox.ShellWaitRequest,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseShellWaitResult, Sandbox.shell.waitForProcess.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__waitForProcess(request, requestOptions));
    }

    private async __waitForProcess(
        request: Sandbox.ShellWaitRequest,
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseShellWaitResult, Sandbox.shell.waitForProcess.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/wait",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellWaitResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.waitForProcess.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.waitForProcess.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Write input to the process in the specified shell session
     *
     * @param {Sandbox.ShellWriteToProcessRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.writeToProcess({
     *         id: "id",
     *         input: "input",
     *         press_enter: true
     *     })
     */
    public writeToProcess(
        request: Sandbox.ShellWriteToProcessRequest,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseShellWriteResult, Sandbox.shell.writeToProcess.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__writeToProcess(request, requestOptions));
    }

    private async __writeToProcess(
        request: Sandbox.ShellWriteToProcessRequest,
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseShellWriteResult, Sandbox.shell.writeToProcess.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/write",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellWriteResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.writeToProcess.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.writeToProcess.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Terminate the process in the specified shell session
     *
     * @param {Sandbox.ShellKillProcessRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.killProcess({
     *         id: "id"
     *     })
     */
    public killProcess(
        request: Sandbox.ShellKillProcessRequest,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseShellKillResult, Sandbox.shell.killProcess.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__killProcess(request, requestOptions));
    }

    private async __killProcess(
        request: Sandbox.ShellKillProcessRequest,
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseShellKillResult, Sandbox.shell.killProcess.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/kill",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellKillResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.killProcess.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.killProcess.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Create a new shell session and return its ID
     * If id already exists, return the existing session
     *
     * @param {Sandbox.ShellCreateSessionRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.createSession()
     */
    public createSession(
        request: Sandbox.ShellCreateSessionRequest = {},
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseShellCreateSessionResponse, Sandbox.shell.createSession.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__createSession(request, requestOptions));
    }

    private async __createSession(
        request: Sandbox.ShellCreateSessionRequest = {},
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseShellCreateSessionResponse, Sandbox.shell.createSession.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/sessions/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellCreateSessionResponse,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.createSession.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.createSession.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Update shell session configuration (e.g., no_change_timeout)
     *
     * @param {Sandbox.ShellUpdateSessionRequest} request
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.updateSession({
     *         id: "id"
     *     })
     */
    public updateSession(
        request: Sandbox.ShellUpdateSessionRequest,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.shell.updateSession.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__updateSession(request, requestOptions));
    }

    private async __updateSession(
        request: Sandbox.ShellUpdateSessionRequest,
        requestOptions?: Shell.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.shell.updateSession.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/sessions/update",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.updateSession.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.updateSession.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Create a new shell session and return the terminal URL
     *
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.getTerminalUrl()
     */
    public getTerminalUrl(
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseStr, Sandbox.shell.getTerminalUrl.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getTerminalUrl(requestOptions));
    }

    private async __getTerminalUrl(
        requestOptions?: Shell.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseStr, Sandbox.shell.getTerminalUrl.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/terminal-url",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseStr,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.getTerminalUrl.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Return aggregate statistics for shell sessions.
     *
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.getSessionStats()
     */
    public getSessionStats(
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseShellSessionStats, Sandbox.shell.getSessionStats.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__getSessionStats(requestOptions));
    }

    private async __getSessionStats(
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseShellSessionStats, Sandbox.shell.getSessionStats.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/sessions/stats",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseShellSessionStats,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.getSessionStats.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * List all active shell sessions
     *
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.listSessions()
     */
    public listSessions(
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseActiveShellSessionsResult, Sandbox.shell.listSessions.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__listSessions(requestOptions));
    }

    private async __listSessions(
        requestOptions?: Shell.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<Sandbox.ResponseActiveShellSessionsResult, Sandbox.shell.listSessions.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/sessions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseActiveShellSessionsResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.listSessions.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Cleanup all active shell sessions
     *
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.cleanupAllSessions()
     */
    public cleanupAllSessions(
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.shell.cleanupAllSessions.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__cleanupAllSessions(requestOptions));
    }

    private async __cleanupAllSessions(
        requestOptions?: Shell.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.shell.cleanupAllSessions.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/shell/sessions",
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.cleanupAllSessions.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Manually cleanup a specific shell session
     *
     * @param {string} sessionId
     * @param {Shell.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.shell.cleanupSession("session_id")
     */
    public cleanupSession(
        sessionId: string,
        requestOptions?: Shell.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.shell.cleanupSession.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__cleanupSession(sessionId, requestOptions));
    }

    private async __cleanupSession(
        sessionId: string,
        requestOptions?: Shell.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.shell.cleanupSession.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/shell/sessions/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.shell.cleanupSession.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.shell.cleanupSession.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
