// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Browser {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Browser {
    protected readonly _options: Browser.Options;

    constructor(_options: Browser.Options) {
        this._options = _options;
    }

    /**
     * Get information about browser, like cdp url, viewport size, etc.
     *
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browser.getInfo()
     */
    public getInfo(
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseBrowserInfoResult, Sandbox.browser.getInfo.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getInfo(requestOptions));
    }

    private async __getInfo(
        requestOptions?: Browser.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseBrowserInfoResult, Sandbox.browser.getInfo.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/info",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseBrowserInfoResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browser.getInfo.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Take a screenshot of the current display.
     *
     * Returns:
     *     StreamingResponse: PNG or JPEG image data with proper headers including display and screenshot dimensions
     */
    public screenshot(
        request: Sandbox.BrowserScreenshotRequest = {},
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<core.BinaryResponse, Sandbox.browser.screenshot.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__screenshot(request, requestOptions));
    }

    private async __screenshot(
        request: Sandbox.BrowserScreenshotRequest = {},
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<core.BinaryResponse, Sandbox.browser.screenshot.Error>>> {
        const { format, quality } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (format != null) {
            _queryParams.format = format;
        }

        if (quality != null) {
            _queryParams.quality = quality.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/screenshot",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browser.screenshot.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browser.screenshot.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Execute a validated action on the current display.
     *
     * @param {Sandbox.Action} request
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browser.executeAction({
     *         action_type: "MOVE_TO",
     *         x: 1.1,
     *         y: 1.1
     *     })
     */
    public executeAction(
        request: Sandbox.Action,
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ActionResponse, Sandbox.browser.executeAction.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__executeAction(request, requestOptions));
    }

    private async __executeAction(
        request: Sandbox.Action,
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ActionResponse, Sandbox.browser.executeAction.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/actions",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ActionResponse,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browser.executeAction.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browser.executeAction.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Execute a validated action on the current display.
     *
     * @param {Sandbox.BrowserConfigRequest} request
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browser.setConfig()
     */
    public setConfig(
        request: Sandbox.BrowserConfigRequest = {},
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.browser.setConfig.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__setConfig(request, requestOptions));
    }

    private async __setConfig(
        request: Sandbox.BrowserConfigRequest = {},
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.browser.setConfig.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/config",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browser.setConfig.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browser.setConfig.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Restart the browser session.
     *
     * - **soft** (default): Reconnect the Playwright session only.
     * - **hard**: Restart the browser process via supervisorctl, optionally
     *   updating URL blocklist/allowlist policies before restart.
     *
     * @param {Sandbox.RestartRequest} request
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browser.restart()
     */
    public restart(
        request?: Sandbox.RestartRequest,
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.browser.restart.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__restart(request, requestOptions));
    }

    private async __restart(
        request?: Sandbox.RestartRequest,
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.browser.restart.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/restart",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request != null ? request : undefined,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.browser.restart.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browser.restart.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Return the current PAC file for proxy split-routing (if configured).
     *
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browser.getProxyPac()
     */
    public getProxyPac(
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<void, Sandbox.browser.getProxyPac.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__getProxyPac(requestOptions));
    }

    private async __getProxyPac(
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<void, Sandbox.browser.getProxyPac.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/proxy.pac",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: undefined,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.browser.getProxyPac.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
