// This file was auto-generated by Fern from our API Definition.

export const AppSchemasFileWatchWaitRequestEventTypesItem = {
    Create: "create",
    Write: "write",
    Remove: "remove",
    Rename: "rename",
    Chmod: "chmod",
} as const;
export type AppSchemasFileWatchWaitRequestEventTypesItem =
    (typeof AppSchemasFileWatchWaitRequestEventTypesItem)[keyof typeof AppSchemasFileWatchWaitRequestEventTypesItem];
