// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface BrowserConfigRequest {
    /** The desired screen resolution, allowed values are: 1920x1080, 640x480, 1360x768, 1280x720, 800x600, 1024x768, 1280x800, 1920x1200, 1280x960, 1400x1050, 1680x1050, 1280x1024, 1600x1200. */
    resolution?: Sandbox.Resolution;
}
