// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {
 *         action: "start"
 *     }
 */
export interface DisplayRecordRequest {
    /** Recording action: start, stop, or status */
    action: Sandbox.DisplayRecordRequestAction;
    /** Output file path (default: /tmp/recordings/recording_{timestamp}.mp4) */
    save_path?: string;
    /** Frames per second */
    fps?: number;
    /** H.264 CRF quality (0=lossless, 51=worst) */
    crf?: number;
    /** Max recording duration in seconds */
    max_duration?: number;
    /** Video width in pixels (auto-detected from X11 if omitted) */
    width?: number;
    /** Video height in pixels (auto-detected from X11 if omitted) */
    height?: number;
}
