// This file was auto-generated by Fern from our API Definition.

export const NavigateRequestWaitUntil = {
    Load: "load",
    Domcontentloaded: "domcontentloaded",
    Networkidle: "networkidle",
    Commit: "commit",
} as const;
export type NavigateRequestWaitUntil = (typeof NavigateRequestWaitUntil)[keyof typeof NavigateRequestWaitUntil];
